# Generated by Django 5.1.4 on 2025-01-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='free_trial_end_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
