# Generated by Django 5.1.4 on 2025-01-08 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_free_trial_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='family_name',
            field=models.CharField(blank=True, help_text='Name of the family member (if applicable).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_family_member',
            field=models.BooleanField(default=False, help_text='Indicates if the user is a family member.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='relationship',
            field=models.CharField(blank=True, help_text='Relationship to the primary user (e.g., spouse, child).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='A short bio for the user.', null=True),
        ),
        migrations.CreateModel(
            name='HSAExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(help_text='The name of the payee.', max_length=100)),
                ('expense_date', models.DateField(help_text='The date the expense was incurred.')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total amount of the expense.', max_digits=10)),
                ('category', models.CharField(choices=[('Pharmacy', 'Pharmacy'), ('Medical', 'Medical'), ('Dental', 'Dental'), ('Vision', 'Vision'), ('Lab Testing', 'Lab Testing'), ('Other', 'Other')], help_text='Category of the expense.', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or details about the expense.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the expense was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the expense was last updated.')),
                ('family_member', models.ForeignKey(blank=True, help_text='The family member associated with this expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
