services:
  web:
    build: .
    command: gunicorn hsatracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: hsatracker_user
      POSTGRES_PASSWORD: vZ%Nvd%d#GJeXnBK@7NS0%CN7hQ79b9^vdVF
      POSTGRES_DB: hsatracker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hsatracker_user -d hsatracker"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
