# Generated by Django 5.1.4 on 2025-01-08 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('dental', 'Dental'), ('vision', 'Vision'), ('prescription', 'Prescription'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(help_text='The user to whom this expense belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('other', 'Other')], max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user to whom this family member belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='expense_family_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='family_member',
            field=models.ForeignKey(blank=True, help_text='The family member associated with this expense (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.familymember'),
        ),
    ]
